config/routes.rb
MovieMarathonHelper::Application.routes.draw do
  get "movies/new"

  resources :users do 
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :movies
  root to: "static_pages#home"

  match 'help', to: 'static_pages#help'
  match 'movie', to: 'static_pages#movie_show'
  match 'signup', to: 'users#new'
  match 'edit', to: 'users#edit'
  match 'signin', to: 'sessions#new'
  match 'signout', to: 'sessions#destroy', via: :delete

end

app/controllers/static_pages_controller.rb
require 'pp'
require 'json'

class StaticPagesController < ApplicationController

  def home
    if signed_in?
    	@micropost = current_user.microposts.build if signed_in?
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def movie_show
    @mv = Movie.new
  	moviename = params[:movie].downcase
  	url = URI.encode("http://www.omdbapi.com/?t=#{moviename}&plot=full")
    url_w_id = URI.encode("http://www.omdbapi.com/?i=#{moviename}&plot=full")
  	@movie = JSON.parse HTTParty.get(url).response.body
    if @movie["Response"] == "True"
      @actors = @movie["Actors"].split(/, */)
      @genres = @movie["Genre"].split(/, */)
    else
      @movie = JSON.parse HTTParty.get(url_w_id).response.body
      if @movie["Response"] == "True"
        @actors = @movie["Actors"].split(/, */)
        @genres = @movie["Genre"].split(/, */)
      end
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<div class="hero-unit center">
<h1 class="logo">Need help?</h1>
<p>You are in the right place. This is the help page.</p>
</div>

app/views/static_pages/home.html.erb
<% if signed_in? %>
<div class="row-fluid">
	<aside class="span4">
		<section>
			<%= render 'shared/user_info' %>
		</section>
		<section>
			<%= render 'shared/stats' %>
		</section>
		<section>
			<%= render 'shared/micropost_form' %>
		</section>
	</aside>
	<div class="span8">
		<div class="hero-unit">
			<h3>Activity feed</h3>
			<%= render 'shared/feed' %>
		</div>
	</div>
</div>
<% else %>
<div class="center hero-unit">
<h1 class="logo">Movie Marathon Helper</h1>
<p>Welcome to Movie Marathon Helper, come here to make managing your movie marathons a breeze!</p>
<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-inverse" %>
</div>
<% end %>

app/views/static_pages/movie_show.html.erb
<% provide(:title, @movie["Title"]) %>
<div class="hero-unit center">
	<% if @movie["Response"] == "True" %>
	<div class="row-fluid">
		<div class="span4">
			<img src="<%= @movie['Poster'] %>" class="img-polaroid">
		</div>
		<div class="span6">
			<h1><%= @movie["Title"] %></h1>
			<p><%= @movie["Plot"] %></p>
			<!--<%= link_to "Add to movies", movies_new_path( movie: @movie["Title"]), class: "btn btn-primary" %> -->
			<%= render 'movies/movie_form' %>
			
		</div>

		<div class="span2 info-box">
			<h3>Movie Info</h3>
			<dl>
				<dt>Title</dt>
				<dd><%= @movie["Title"] %></dd>

				<dt>Release date</dt>
				<dd><%= @movie["Released"] %></dd>

				<dt>Runtime</dt>
				<dd><%= @movie["Runtime"] %></dd>

				<dt>Director</dt>
				<dd><%= @movie["Director"]%></dd>

				<dt>Writer</dt>
				<dd><%= @movie["Writer"] %></dd>
		
				<dt>Actors</dt>
				<% for actor in @actors do %>
				<dd><%= actor %></dd>
				<% end %>

				<dt>Genres</dt>
				<% for genre in @genres do %>
				<dd><%= genre %></dd>
				<% end %>

				<dt>IMDB rating</dt>
				<dd><%= @movie["imdbRating"] %></dd>
			</dl>
		</div>
	</div>
	<% else %>
		<h1>Nothing found!</h1>
		<p>There were no results with the search word you entered!</p>
	<% end %>
</div>