config/routes.rb
MovieMarathonHelper::Application.routes.draw do
  get "movies/new"

  resources :users do 
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :movies
  root to: "static_pages#home"

  match 'help', to: 'static_pages#help'
  match 'movie', to: 'static_pages#movie_show'
  match 'signup', to: 'users#new'
  match 'edit', to: 'users#edit'
  match 'signin', to: 'sessions#new'
  match 'signout', to: 'sessions#destroy', via: :delete

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize object.errors.count, "error" %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items, class: "pagination pagination-centered" %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
<span class="content">
	<%= feed_item.content %>
</span>
<span class="timestamp">
<small>
	<em>Posted <%= time_ago_in_words feed_item.created_at %> ago </em>
	<% if current_user? feed_item.user %>
		<%= link_to "delete", feed_item, method: :delete, data: { confirm: "Delete post?" }, title: feed_item.content %>
	<% else %>
	 <em>by</em> <%= link_to feed_item.user.name, feed_item.user %>
	<% end %>
</small>
</span>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<%= f.text_area :content, placeholder: "New post.." %>
	<%= f.submit "Post", class: "btn btn-large btn-inverse" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
	<strong id ="followers" class="stat">
		<%= @user.followed_users.count %>
	</strong>
	Following
	</a>
	<a href="<%= followers_user_path(@user) %>">
	<strong>
		<%= @user.followers.count %>
	</strong>
	Followers
	</a>
</div>

app/views/shared/_user_info.html.erb
<h1 class="logo"><%= current_user.name %></h1>
<span>
	<%= link_to "View my profile", current_user %>
</span>
<em>
	<%= pluralize(current_user.microposts.count, "post") %>
</em>