config/routes.rb
MovieMarathonHelper::Application.routes.draw do
  get "movies/new"

  resources :users do 
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :movies
  root to: "static_pages#home"

  match 'help', to: 'static_pages#help'
  match 'movie', to: 'static_pages#movie_show'
  match 'signup', to: 'users#new'
  match 'edit', to: 'users#edit'
  match 'signin', to: 'sessions#new'
  match 'signout', to: 'sessions#destroy', via: :delete

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>Based on <a href="http://news.railstutorial.org/">Michael Hartl's Rails Tutorial</a></small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container-fluid">
			<a class="brand logo" href="<%= root_path %>">Movie Marathon Helper</a>
			<nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "Help",    help_path %></li>
              <% if signed_in? %>
              	<li><%= link_to "Marathon Men", users_path %></li>
                <li><%= link_to "Movies", movies_path%></li>
                <div class="navbar-form pull-left no_margin">
                <%= form_tag controller: "static_pages", action: "movie_show" do %>
                  <%= text_field_tag :movie,nil ,placeholder: 'Movie title or imdbID', class: "span3" %>
                  <%= submit_tag("Search movie", class: "btn btn-inverse") %>
                <% end %>
                </div>
              	<li id="fat-menu" class="dropdown">
              		<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
              	<ul class="dropdown-menu">
              		<li><%= link_to "Profile", current_user %></li>
              		<li><%= link_to "Settings", edit_user_path(current_user) %></li>
              		<li class="divider"></li>
              		<li>
                  		<%= link_to "Sign out", signout_path, method: "delete" %>
                	</li>
              	</ul>
              </li>
              <% else %>
        		<li><%= link_to "Sign in", signin_path %></li>
              <% end %>
            </ul>
          </nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href='https://fonts.googleapis.com/css?family=Butcherman' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Noticia+Text' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'prototype' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container-fluid">
	<% flash.each do |key,value| %>
		<div class="alert alert-<%= key %>"><%= value %></div>
	<% end %>
	<%= yield %>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>